= Introduction to Java Logging

== 1. 개요

* 프로그램의 런타임 동작을 이해하고 디버그하는 데 강력한 도구
* 로그는 중요한 데이터를 *캡처하고 보존하여 언제든지 분석*
* log4j2, logback, log4j
** 인기 있는 자바 로깅 프레임워크으로 설명
* slf4j
** 다양한 로깅 프레임워크에 대한 공통 인터페이스를 제공

== 2. 로깅 활성화

프로젝트 내에서 로깅을 활성화하려면 다음 세 가지 공통 단계를 따름

. 필요한 라이브러리 추가
. 설정
. 로그 문장 삽입


== 3. Log4j2

* Log4j logging framework의 개선된 버전
* 비동기 로깅 가능
* Log4j2 사용을 위한 라이브러리
+
[source,xml]
----
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-api</artifactId>
    <version>2.6.1</version>
</dependency>
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-core</artifactId>
    <version>2.6.1</version>
</dependency>
----
** log4j2 최신 버전은 link:https://logging.apache.org/log4j/2.x/[log4j 2.x]

=== 3.1. 설정

* 기본 설정 파일 log4j2.xml

* appender(어펜더)
** 로그 메시지를 어디로 보낼지 결정
** 대상은 콘솔, 파일, 소켓 등
+
[source,xml]
----
<Configuration status="debug" name="nhnacademy" packages="">
    <Appenders>
        <Console name="stdout" target="SYSTEM_OUT">
            <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss} %p %m%n"/>
        </Console>
    </Appenders>
</Configuration>
----
** 이름 지정 가능
** PatternLayout
*** 메시지 출력 형식 지정
*** %d는 날짜 패턴, %p는 로그 레벨 출력, %m은 로그 메시지 출력, %n은 새 줄 기호 추가
*** 자세한 정보는 link:https://logging.apache.org/log4j/2.x/manual/layouts.html#pattern-layout[Pattern Layout]
** 활성화하려면 <Loggers> 섹션에 추가
+
[source,xml]
----
<Loggers>
    <Root level="error">
        <AppenderRef ref="STDOUT"/>
    </Root>
</Loggers>
----

=== 3.2. 파일로 로깅

* 파일로 로깅을 사용해야 할 때
* 설정에 파일 출력을 위한 appender 추가
+
[source,xml]
----
<Appenders>
    <File name="fout" fileName="test.log" append="true">
        <PatternLayout>
            <Pattern>%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n</Pattern>
        </PatternLayout>
    </File>
</Appenders>
----
* File appender 매개변수 추가 설정
** file - 로그 파일 이름
** append - 기본적으로 기존 파일에 추가
* 활성화를 위해서는 <Loggers> 내 <Root> 섹션에 추가
+
[source,xml]
----
<Root level="INFO">
    <AppenderRef ref="stdout" />
    <AppenderRef ref="fout"/>
</Root>
----

=== 3.3. 비동기 로깅

* link:https://lmax-exchange.github.io/disruptor/[LMAX disruptor(디스럽터)] 라이브러리 추가
** 락-프리 스레드 간 통신 라이브러리
** pom.xml에 추가
+
[source,xml]
----
<dependency>
    <groupId>com.lmax</groupId>
    <artifactId>disruptor</artifactId>
    <version>3.3.4</version>
</dependency>
----
** 설정에서 <Root> 대신 <asyncRoot> 사용
+
[source,xml]
----
<AsyncRoot level="DEBUG">
    <AppenderRef ref="stdout" />
    <AppenderRef ref="fout"/>
</AsyncRoot>
----
* 또는 시스템 속성 Log4jContextSelector를 org.apache.logging.log4j.core.async.AsyncLoggerContextSelector로 설정

=== 3.4. 사용법

[source, java]
----
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class Log4jExample {

    private static Logger logger = LogManager.getLogger(Log4jExample.class);

    public static void main(String[] args) {
        logger.debug("Debug log message");
        logger.info("Info log message");
        logger.error("Error log message");
    }
}
----

* 실행 후, 애플리케이션은 콘솔과 파일에 다음 메시지 기록
+
[source,console]
----
2016-06-16 17:02:13 INFO  Info log message
2016-06-16 17:02:13 ERROR Error log message
----
* 루트 로그 레벨을 ERROR로 높이면
+
[source,xml]
----
<level value="ERROR" />
----
+
** 출력은
+
[source,console]
----
2016-06-16 17:02:13 ERROR Error log message
----
* logger.error는 exception 로깅에 사용 가능
+
[source,console]
----
try {
    // Here some exception can be thrown
} catch (Exception e) {
    logger.error("Error log message", throwable);
}
----

=== 3.5. 패키지 레벨 구성

* 특정 패키지 예를 들어 com.nhnacademy.log4j2에서 TRACE 로그 레벨의 메시지를 표시해야 하는 경우:
+
[source,console]
----
logger.trace("Trace log message");
----
* 하나의 패키지만 로깅을 활성화하려면 log4j2.xml에서 <Root> 전에 다음 섹션 추가
+
[source,xml]
----
<Logger name="com.nhnacademy.log4j2" level="debug" additivity="false">
    <AppenderRef ref="stdout"/>
</Logger>
----
* 이는 com.nhnacademy.log4j 패키지에 대한 로깅 활성화 후 출력
+
[source,console]
----
2016-06-16 17:02:13 TRACE Trace log message
2016-06-16 17:02:13 DEBUG Debug log message
2016-06-16 17:02:13 INFO  Info log message
2016-06-16 17:02:13 ERROR Error log message
----
** Logger 섹션에 **additivity="false"로 설정하지 않을 경우, 동일한 로그가 2번 출력될 수 있음**

=== 3.6. 예제

* link:./../example/logging_log4j2/pom.xml[logging_log4j2/pom.xml]
* link:./../example/logging_log4j2/src/main/resources/log4j2.xml[logging_log4j2/src/main/java/resources/log4j2.xml]
* link:./../example/logging_log4j2/src/main/java/com/nhnacademy/Log4jExample.java[logging_log4j2/src/main/java/com/nhnacademy/Log4jExample.java]
* link:./../example/logging_log4j2/src/main/java/com/nhnacademy/modules/SubModule.java[logging_log4j2/src/main/java/com/nhnacademy/modules/SubModule.java]

== 4. Logback

* Log4j를 개발한 동일한 개발자가 만든 Log4j의 개선 버전
* Log4j보다 많은 기능을 가지고 있으며, 그 중 많은 기능이 Log4j2에 도입
* Logback의 모든 장점을 link:https://logback.qos.ch/[공식 사이트]에서 확인
* pom.xml에 다음 종속성 추가
+
[source,xml]
----
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.6</version>
</dependency>
----
** logback-core와 slf4j-api라는 두 가지 종속성을 자동으로 가져옴

=== 4.1. 설정

* Logback 설정
+
[source,xml]
----
<configuration>
  <!-- 콘솔 어펜더 -->
  <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
    <layout class="ch.qos.logback.classic.PatternLayout">
      <!-- 콘솔 어펜더용 로그 메시지 패턴 -->
      <Pattern>%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n</Pattern>
    </layout>
  </appender>

  <!-- 파일 어펜더 -->
  <appender name="fout" class="ch.qos.logback.core.FileAppender">
    <file>test.log</file>
    <append>false</append>
    <encoder>
      <!-- 파일 어펜더용 로그 메시지 패턴 -->
      <pattern>%d{yyyy-MM-dd HH:mm:ss} %-5p %m%n</pattern>
    </encoder>
  </appender>

  <!-- 지정된 패키지의 로그 레벨 재정의 -->
  <logger name="com.nhnacademy.modules" level="TRACE"/>

  <root level="INFO">
    <appender-ref ref="stdout" />
    <appender-ref ref="fout" />
  </root>
</configuration>
----
* Logback은 SLF4J를 인터페이스로 사용하므로 SLF4J의 Logger와 LoggerFactory import

=== 4.2. 사용법

* Logback은 SLF4J를 네이티브 API로 사용
* Logback 로깅을 사용하는 예제
+
[source,java]
----
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Log4jExample {

    private static Logger logger = LoggerFactory.getLogger(Log4jExample.class);

    public static void main(String[] args) {
        logger.debug("Debug log message");
        logger.info("Info log message");
        logger.error("Error log message");
    }
}
----

=== 4.3. 예제

* link:./../example/logging_logback/pom.xml[logging_logback/pom.xml]
* link:./../example/logging_logback/src/main/resources/logback.xml[logging_logback/src/main/java/resources/logback.xml]
* link:./../example/logging_logback/src/main/java/com/nhnacademy/LogbackExample.java[logging_logback/src/main/java/com/nhnacademy/LogbackExample.java]
* link:./../example/logging_logback/src/main/java/com/nhnacademy/modules/SubModule.java[logging_logback/src/main/java/com/nhnacademy/modules/SubModule.java]

=== 5. SLF4J

* 대부분의 자바 로깅 프레임워크에 대한 공통 인터페이스와 추상화 제공
* 파사드 역할을 하며 로깅 프레임워크의 기본 기능에 접근하기 위한 표준화된 API 제공

==== 5.1. slf4j for log4j2

* 의존성 주입에 따라 변경
+
[source,xml]
----
<dependency>
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-slf4j-impl</artifactId>
    <version>2.10.0</version>
</dependency>
----

=== 5.2. slf4j for log4j2 예제

* link:./../example/logging_slf4j_log4j2/pom.xml[logging_slf4j_log4j2/pom.xml]
* link:./../example/logging_slf4j_log4j2/src/main/resources/log4j2.xml[logging_slf4j_log4j2/src/main/java/resources/log4j2.xml]
* link:./../example/logging_slf4j_log4j2/src/main/java/com/nhnacademy/Slf4jExample.java[logging_slf4j_log4j2/src/main/java/com/nhnacademy/Slf4jExample.java]
* link:./../example/logging_slf4j_log4j2/src/main/java/com/nhnacademy/modules/SubModule.java[logging_slf4j_log4j2/src/main/com/nhnacademy/modules/SubModule.java]

==== 5.3. slf4j for log4j2

* log4j2 설정 참조

---

ifndef::github-env[]
link:../index.adoc[목록]
endif::[]

ifdef::github-env[]
link:../README.adoc[목록]
endif::[]
